### PR TITLE
Blog App: validations, model specs, and n+1 problems

### PR DESCRIPTION
**Pull request by Nuri1977**
### Validations, model specs, and n+1 problems

- Implemented the following validations:
  - For the User model:
    - Name must not be blank.
    - PostsCounter must be an integer greater than or equal to zero.
  - For the Post model:
    - Title must not be blank.
    - Title must not exceed 250 characters.
    - CommentsCounter must be an integer greater than or equal to zero.
    - LikesCounter must be an integer greater than or equal to zero.
- Added unit specs for all of your models' methods and validations.
- Added flash messages in the create actions in all your controllers.
- The N+1 problem is solved when fetching all posts and their comments for a user.

### CODE REVIEW

**Review by mmsesay — CHANGES_REQUESTED** [review]
Hi @Nuri1977, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mmsesay** [comment]
- [ ] Inside your post controller index method. Please refactor the codes in the screenshot to the suggested code below in order to solve the N+1 query problem

Screenshot |
:--------------:|
a1

Suggested Code

```ruby
def index
   @user = User.find(params[:user_id])
   @posts = @user.posts.includes(:comments)
end
```

**Comment by Nuri1977** [comment]
I already fixed N+1 query in post#index view 
` <% post.recent_comments.includes(:author).each do |comment| %>`
`    <p><%= comment.author.name %>: <%= comment.text %></p>`
`<% end %>`
and post#show view
`      <% @post.comments.includes(:author).each do |comment| %>`
       ` <p><%= comment.author.name %>: <%= comment.text %></p>`
      `<% end %>`

**Review by mikethreels — APPROVED** [review]
Hi Nuri, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
